### ISSUE TITLE
How to include this calendar into some view controller?

### ISSUE THREAD

**Issue by amixpal** [bananaRanger/AYCalendar#1]
I am looking for a way to include this calendar into some ViewController but it's opening as a separate new screen. Is there any way that I can include into any view controller? 

or

`  ```
func didSelect(date: Date?, on calendar: AYCalendarViewController) {
              let storyboard = UIStoryboard(name: viewControllerState.TAB_BAR, bundle: nil)
             let controller = storyboard.instantiateViewController(withIdentifier: 
            "ChooseTimeAndDateViewController") as! ChooseTimeAndDateViewController
            self.navigationController?.pushViewController(controller, animated: true)
    }`

```
It's not navigating to a new controller. How can I navigate it?

**Comment by bananaRanger** [comment]
You can do it like that:

```
import AYCalendar

class ViewController: UIViewController {

  @IBOutlet weak var calendarContainerView: UIView!
  
  let calendar = AYCalendarViewController()

  override func viewDidLoad() {
    super.viewDidLoad()
    
    calendar.delegate = self
    calendar.dataSource = self
    calendar.uiDelegate = self
    
    calendarContainerView.addSubview(calendar.view)
    calendarContainerView.addAllSidesAnchors(to: calendar.view)
  }

}
```

**Comment by amixpal** [comment]
Thanks for providing the code I can see the calendar but in that case, Delegate methods are not working. Debug point is not coming inside didSelect() method

**Comment by bananaRanger** [comment]
can you show how you use ```AYCalendarViewController``` instance?

**Comment by amixpal** [comment]
```
 @IBOutlet var calendarView: UIView!
 override func viewDidAppear(_ animated: Bool) {
          super.viewDidAppear(animated)
```

    let calendar = AYCalendarViewController()
        calendarView.addSubview(calendar.view)
        calendarView.addAllSidesAnchors(to: calendar.view)
        continueButtonView.layer.cornerRadius = 10

        
        calendar.delegate = self
        calendar.uiDelegate = self
        calendar.dataSource = self
        
        calendar.monthNavigationView?.backgroundColor = .clear
        calendar.monthNavigationView?.lblText.textColor = UIColor(red:0.28, green:0.28, blue:0.28, alpha:1.0)
        calendar.monthNavigationView?.btnNext.backgroundColor = .white
        calendar.monthNavigationView?.btnPrev.backgroundColor = .white
        
        calendar.monthNavigationView?.layer.cornerRadius = 8
        calendar.monthNavigationView?.layer.shadowRadius = 10
        calendar.monthNavigationView?.layer.shadowOpacity = 0.2
        
        calendar.calendarSlides.backgroundColor = .white
        
        calendar.calendarSlides.layer.shadowColor = UIColor.white.cgColor
        calendar.calendarSlides.layer.cornerRadius = 8
        calendar.calendarSlides.layer.shadowRadius = 10
        calendar.calendarSlides.layer.shadowOpacity = 0.25
    }`

```
extension SelectStartDateForWorkoutViewController: AYCalendarUIDelegate, AYCalendarDelegate, AYCalendarDataSource {
 func didSelect(date: Date?, on calendar: AYCalendarViewController) {
    print("selected date")
}
```

**Comment by bananaRanger** [comment]
You should store ```let calendar = AYCalendarViewController()``` as a property. So if you move this line and put it after ```@IBOutlet var calendarView: UIView!```, for example, it will work as expect.

**Comment by amixpal** [comment]
oh! my bad. It's working perfectly.
